version: '3'

networks:
  nats-net:
    driver: bridge

volumes:
  data:

services:
  nats:
    image: nats:2.10.2
    restart: always
    container_name: nats
    networks:
      - nats-net
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    volumes:
      - ./data:/data
