version: '3'

services:
  etcd:
    image: bitnami/etcd:3.5
    container_name: etcd
    restart: always
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379"
      - ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCDCTL_API="3"
    ports:
      - 2379:2379
      - 2380:2380
      - 4001:4001
    volumes: 
      - ./data:/default.etcd
