version: '3'

services:
  etcd:
    image: docker.io/bitnami/etcd:3.5
    restart: always
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - data:/bitnami/etcd
volumes:
  data:
    driver: local
