version: "3.1"
services:
  postgreis:
    image: postgres:15.4
    container_name: postgres15
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: ripper
      POSTGRES_DB: postgres
      TZ: Asia/Shanghai
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

