version: '3'

networks:
  redis-net:
    driver: bridge

volumes:
  data:

services:
  redis:
    image: redis:7.2.0
    restart: always
    container_name: redis7
    networks:
      - redis-net
    ports:
      - '6379:6379'
    command:
      redis-server /etc/redis/redis.conf
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis/redis.conf
